#!/usr/bin/env python3
"""Regenerate gas/* for MIDISC2.1 from release21.json and prove each cluster.

MIDISC2.0/2.1 ship as a hash-checked MAIN patch (tools/midisc/release21.json),
not the 8.x Python encoder path in tools/gas_port.py. This script:

  1. Applies release21.json to stock 1.40C MAIN
  2. Writes gas/msc21_{a,b,c,ram}.s + gas/msc21.s (engine_follow / msc_follow)
     — only bytes release21 writes; gaps are `.skip N` (zeros, never stock)
  3. Assembles each cluster at his address; proves only the written bytes
  4. Writes tools/midisc/hooks21.py (stock-site Detours/Pokes)

Symbols KITS needs: msc_kit_commit, msc_follow, engine_follow (+ playback_step).

Requires OCTABAM=<octabam checkout> so arena sites are skipped from hooks21.

    OCTABAM=~/octabam PYTHONPATH=tools python3 tools/gas_port21.py
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from midisc.release21 import patch  # noqa: E402
from midisc.util import ensure_stock  # noqa: E402

B = 0x40000400
RAM0, RAMN = 0x40A955E0, 12 * 6144
GAS = ROOT / "gas"
HOOKS_OUT = ROOT / "tools" / "midisc" / "hooks21.py"

EXPORTS = {
    "reload": 0x400D653E,
    "clr_pt": 0x400E1EC4,
    "msc_kit_commit": 0x400D736E,
    "playback_step": 0x400D6E7E,
}

GLUE = r"""| MIDISC2.1 glue: playback follow + KITS msc_follow.
| Regenerated by tools/gas_port21.py — do not edit by hand.

        .text
        .globl  engine_follow, msc_follow

        .set    PLAY_BANK, msc21_b+(0x400d6d60-0x400d24d0)
        .set    PLAY_PART, msc21_b+(0x400d6d64-0x400d24d0)
        .set    XF_CONTEXT_VALID, msc21_b+(0x400d68b8-0x400d24d0)

engine_follow:
        lea     %sp@(-12),%sp
        moveml  %d0-%d2,%sp@
        moveq   #1,%d0
        cmpl    0x800065b8,%d0
        bne.s   9f
        moveq   #0,%d0
        moveb   0x80001828,%d0
        cmpil   #15,%d0
        bhi.s   9f
        moveq   #0,%d1
        moveb   0x80001829,%d1
        cmpil   #3,%d1
        bhi.s   9f
        movel   #0x9b340,%d2
        mulsl   %d2,%d0
        addil   #0x400e21e0,%d0
        cmpl    PLAY_BANK,%d0
        bne.s   1f
        cmpl    PLAY_PART,%d1
        beq.s   9f
1:      movel   %d0,PLAY_BANK
        movel   %d1,PLAY_PART
        clrl    XF_CONTEXT_VALID
9:      moveml  %sp@,%d0-%d2
        lea     %sp@(12),%sp
        jmp     playback_step

msc_follow:
        lea     %sp@(-12),%sp
        moveml  %d0-%d2,%sp@
        cmpil   #3,%d0
        bhi.s   9f
        cmpil   #15,%d1
        bhi.s   9f
        movel   #0x9b340,%d2
        mulsl   %d2,%d1
        addil   #0x400e21e0,%d1
        cmpl    PLAY_BANK,%d1
        bne.s   1f
        cmpl    PLAY_PART,%d0
        beq.s   9f
1:      movel   %d1,PLAY_BANK
        movel   %d0,PLAY_PART
        clrl    XF_CONTEXT_VALID
9:      moveml  %sp@,%d0-%d2
        lea     %sp@(12),%sp
        rts
"""


def u32(b: bytes, a: int) -> int:
    return int.from_bytes(b[a - B : a - B + 4], "big")


def arena_ops() -> set[int]:
    octabam = os.environ.get("OCTABAM")
    if not octabam:
        sys.exit("set OCTABAM=<octabam checkout>")
    tools = Path(octabam) / "tools"
    if not tools.is_dir():
        sys.exit("OCTABAM=%s: no tools/ directory" % octabam)
    sys.path.insert(0, str(tools))
    from remix import arena  # type: ignore

    ops: set[int] = set()
    for s in arena.BASE_SITES:
        ops.update(range(s + 2, s + 6))
    for s, _ in arena.DERIVED_SITES:
        ops.update(range(s + 2, s + 6))
    for s, _, _ in (arena.COUNT_SITE, arena.FILL_SITE, arena.CLEAR_SITE, arena.CAP_SITE):
        ops.update(range(s, s + 4))
    return ops


def written_addrs(spec: dict) -> set[int]:
    """Runtime addresses that release21.json actually patches."""
    written: set[int] = set()
    for off, h in spec["writes"]:
        n = len(h) // 2
        written.update(range(B + off, B + off + n))
    return written


def diff_regions(stock: bytes, main: bytes):
    regs, i, n = [], 0, len(stock)
    while i < n:
        if stock[i] != main[i]:
            j = i
            while j < n and (stock[j] != main[j] or stock[j : j + 8] != main[j : j + 8]):
                j += 1
            regs.append((B + i, B + j))
            i = j
        else:
            i += 1
    return regs


def clusters_from(caves):
    clusters = []
    for a, e in caves:
        if clusters and a - clusters[-1][1] < 0x8000:
            clusters[-1][1] = e
        else:
            clusters.append([a, e])
    return [(a & ~3, (e + 3) & ~3) for a, e in clusters]


def emit_cluster(a: int, e: int, nm: str, main_img: bytes, written: set[int],
                 target, sym) -> list[str]:
    """Emit one cluster: release21 bytes as .byte/.long; gaps as .skip N."""
    out = [
        "| MIDISC2.1 cave cluster %s @ 0x%08x..0x%08x." % (nm.upper(), a, e),
        "| Generated from release21.json by tools/gas_port21.py. Do not edit.",
        "| Gaps release21 does not write are .skip (zeros) — never stock bytes.",
        "        .text",
        "        .balign 4",
        "        .globl msc21_%s" % nm,
        "msc21_%s:" % nm,
    ]
    p = a
    row: list[int] = []

    def flush_bytes():
        if row:
            out.append("        .byte " + ",".join("0x%02x" % x for x in row))
            row.clear()

    while p < e:
        # Absolute pointer into caves/RAM → relocatable .long
        if (
            p % 2 == 0
            and p + 4 <= e
            and all((p + i) in written for i in range(4))
            and target(u32(main_img, p))
        ):
            flush_bytes()
            out.append("        .long %s" % sym(u32(main_img, p)))
            p += 4
            continue
        if p in written:
            row.append(main_img[p - B])
            if len(row) == 16:
                flush_bytes()
            p += 1
            continue
        # Unwritten run → .skip (zeros; layout preserved for PC-relative branches)
        flush_bytes()
        n = 0
        while p < e and p not in written:
            # Don't start a .long mid-skip; skip bytes are never written
            n += 1
            p += 1
        out.append("        .skip %d" % n)
    flush_bytes()
    return out


def main() -> int:
    for t in ("m68k-elf-as", "m68k-elf-ld", "m68k-elf-objcopy"):
        if not __import__("shutil").which(t):
            sys.exit(f"need {t}")
    # Fail early: hooks need octabam's arena module
    aops = arena_ops()

    stock = ensure_stock()
    main_img = patch(stock)
    spec = json.loads((ROOT / "tools/midisc/release21.json").read_text())
    if hashlib.sha256(main_img).hexdigest() != spec["main_sha256"]:
        sys.exit("release21 patch integrity failure")
    written = written_addrs(spec)

    regs = diff_regions(stock, main_img)
    caves = [r for r in regs if r[0] >= 0x400C4000]
    hook_regs = [r for r in regs if r[0] < 0x400C4000]
    clusters = clusters_from(caves)
    if len(clusters) != 3:
        sys.exit(f"expected 3 clusters, got {clusters}")
    names = "abc"

    def target(v: int) -> bool:
        return (RAM0 <= v < RAM0 + RAMN) or any(a <= v < e for a, e in clusters)

    def sym(v: int) -> str:
        if RAM0 <= v < RAM0 + RAMN:
            return "msc21_ram+0x%x" % (v - RAM0)
        for k, (a, e) in enumerate(clusters):
            if a <= v < e:
                return "msc21_%s+0x%x" % (names[k], v - a)
        raise ValueError(hex(v))

    GAS.mkdir(exist_ok=True)
    for stale in GAS.glob("*.s"):
        if stale.name.startswith("msc21") or stale.name in {
            "cave2.s", "code2.s", "enc_unlock.s", "msc.s", "project_cave.s",
            "reload_cave.s", "safe_cave.s", "scene_paste.s", "seam.s",
            "seam_bank.s", "state.s", "stub.s", "voice_reload.s",
        }:
            stale.unlink()

    proofs = []
    for k, (a, e) in enumerate(clusters):
        nm = names[k]
        out = emit_cluster(a, e, nm, main_img, written, target, sym)
        for name, v in EXPORTS.items():
            if a <= v < e:
                out += ["        .globl %s" % name, "        .set %s, %s" % (name, sym(v))]
        (GAS / ("msc21_%s.s" % nm)).write_text("\n".join(out) + "\n")
        proofs.append((nm, a, e))

    (GAS / "msc21_ram.s").write_text(
        "| MIDISC2.1 private RAM (12 arena pages). Linker-owned.\n"
        "        .text\n        .balign 16\n        .globl msc21_ram\nmsc21_ram:\n"
        "        .fill 4096,1,0xff\n        .fill %d,1,0\n" % (RAMN - 4096)
    )
    (GAS / "msc21.s").write_text(GLUE)

    # Prove: only bytes release21 wrote must match; gaps assemble to zero.
    defs = ["--defsym=msc21_ram=0x%x" % RAM0] + [
        "--defsym=msc21_%s=0x%x" % (names[k], c[0]) for k, c in enumerate(clusters)
    ]
    with tempfile.TemporaryDirectory() as td:
        for nm, a, e in proofs:
            o = os.path.join(td, nm + ".o")
            el = os.path.join(td, nm + ".elf")
            bn = os.path.join(td, nm + ".bin")
            subprocess.check_call(["m68k-elf-as", "-mcpu=5475", "-o", o, str(GAS / ("msc21_%s.s" % nm))])
            d = [x for x in defs if not x.startswith("--defsym=msc21_%s=" % nm)]
            subprocess.check_call(
                ["m68k-elf-ld", "-Ttext=0x%x" % a, *d, "-o", el, o],
                stderr=subprocess.DEVNULL,
            )
            subprocess.check_call(["m68k-elf-objcopy", "-O", "binary", "-j", ".text", el, bn])
            got = Path(bn).read_bytes()
            want = main_img[a - B : e - B]
            if len(got) != len(want):
                sys.exit(
                    "gas_port21: cluster %s size %d != %d" % (nm, len(got), len(want))
                )
            for i in range(len(want)):
                addr = a + i
                if addr in written:
                    if got[i] != want[i]:
                        sys.exit(
                            "gas_port21: cluster %s written byte @0x%08x: got %02x want %02x"
                            % (nm, addr, got[i], want[i])
                        )
                else:
                    if got[i] != 0:
                        sys.exit(
                            "gas_port21: cluster %s gap @0x%08x must be zero, got %02x"
                            % (nm, addr, got[i])
                        )
            n_w = sum(1 for i in range(len(want)) if (a + i) in written)
            print(
                "PROOF OK  msc21_%s  0x%08x..0x%08x  %d B layout, %d written == release21"
                % (nm, a, e, len(want), n_w)
            )

    # hooks (arena sites already loaded)
    labels: dict[int, str] = {}
    det, pok = [], []
    for a, e in hook_regs:
        diff = [q for q in range(a, e) if main_img[q - B] != stock[q - B]]
        if diff and all(q in aops for q in diff):
            continue
        if any(q in aops for q in diff):
            continue
        if a <= 0x400A4BA0 < e:
            continue
        covered: set[int] = set()
        q = (a - 4) & ~1
        while q < e:
            v = u32(main_img, q)
            if q + 4 > a and target(v) and v != u32(stock, q):
                site = q - 2
                op = main_img[site - B : site - B + 2]
                sop = stock[site - B : site - B + 2]
                span = 6
                while site + span < e and main_img[site - B + span : site - B + span + 2] == b"\x4e\x71":
                    span += 2
                if op == b"\x4e\xf9":
                    kind = "jmp"
                elif op == b"\x4e\xb9":
                    kind = "jsr"
                else:
                    if op != sop:
                        q += 2
                        continue
                    kind = "lea"
                if kind in ("jmp", "jsr") and op != sop and span == 6 and e > site + 6:
                    span = (e - site + 1) & ~1
                lab = "h_%08x" % v
                labels[v] = lab
                det.append((site, stock[site - B : site - B + span], lab, kind, span))
                covered.update(range(site, site + span))
                q = site + span
                continue
            q += 2
        rest = [x for x in range(a, e) if x not in covered and main_img[x - B] != stock[x - B]]
        if rest:
            s0, s1 = min(rest), max(rest) + 1
            pok.append((s0, stock[s0 - B : s1 - B], main_img[s0 - B : s1 - B]))

    for k, (a, e) in enumerate(clusters):
        f = GAS / ("msc21_%s.s" % names[k])
        extra = []
        for v, lab in sorted(labels.items()):
            if a <= v < e:
                extra += ["        .globl %s" % lab, "        .set %s, %s" % (lab, sym(v))]
        if extra:
            f.write_text(f.read_text() + "\n".join(extra) + "\n")

    def unit_of(v: int) -> str:
        return "msc21_%s" % names[[k for k, (a, e) in enumerate(clusters) if a <= v < e][0]]

    H = lambda b: b.hex()
    lines = [
        "# GENERATED by tools/gas_port21.py -- MIDISC2.1 stock-site rewrites.",
        "H = bytes.fromhex",
        "",
        "def hooks(Detour, Poke):",
        "    D = (",
    ]
    for site, exp, lab, kind, span in det:
        v = int(lab[2:], 16)
        pad = ", pad_to=%d" % span if span > 6 else ""
        lines.append(
            '        Detour(0x%08X, H("%s"), "%s", "%s", "his %s -> 0x%08x", kind="%s"%s),'
            % (site, H(exp), unit_of(v), lab, kind, v, kind, pad)
        )
    lines.append("    )")
    lines.append("    P = (")
    for s0, a_, b_ in pok:
        lines.append('        Poke(0x%08X, H("%s"), H("%s"), "his"),' % (s0, H(a_), H(b_)))
    lines.append("    )")
    lines.append("    return D, P")
    HOOKS_OUT.write_text("\n".join(lines) + "\n")

    print("wrote", sorted(p.name for p in GAS.glob("*.s")))
    print("wrote", HOOKS_OUT.relative_to(ROOT), "(%d detours, %d pokes)" % (len(det), len(pok)))
    print("symbols: engine_follow, msc_follow, msc_kit_commit, playback_step, reload, clr_pt")
    print("written bytes match release21; gaps are zero (.skip)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
