| MIDISC2.1 glue: playback follow + KITS msc_follow.
| Regenerated by tools/gas_port21.py — do not edit by hand.

        .text
        .globl  engine_follow, msc_follow

        .set    PLAY_BANK, msc21_b+(0x400d6d60-0x400d24d0)
        .set    PLAY_PART, msc21_b+(0x400d6d64-0x400d24d0)
        .set    XF_CONTEXT_VALID, msc21_b+(0x400d68b8-0x400d24d0)

engine_follow:
        lea     %sp@(-12),%sp
        moveml  %d0-%d2,%sp@
        moveq   #1,%d0
        cmpl    0x800065b8,%d0
        bne.s   9f
        moveq   #0,%d0
        moveb   0x80001828,%d0
        cmpil   #15,%d0
        bhi.s   9f
        moveq   #0,%d1
        moveb   0x80001829,%d1
        cmpil   #3,%d1
        bhi.s   9f
        movel   #0x9b340,%d2
        mulsl   %d2,%d0
        addil   #0x400e21e0,%d0
        cmpl    PLAY_BANK,%d0
        bne.s   1f
        cmpl    PLAY_PART,%d1
        beq.s   9f
1:      movel   %d0,PLAY_BANK
        movel   %d1,PLAY_PART
        clrl    XF_CONTEXT_VALID
9:      moveml  %sp@,%d0-%d2
        lea     %sp@(12),%sp
        jmp     playback_step

msc_follow:
        lea     %sp@(-12),%sp
        moveml  %d0-%d2,%sp@
        cmpil   #3,%d0
        bhi.s   9f
        cmpil   #15,%d1
        bhi.s   9f
        movel   #0x9b340,%d2
        mulsl   %d2,%d1
        addil   #0x400e21e0,%d1
        cmpl    PLAY_BANK,%d1
        bne.s   1f
        cmpl    PLAY_PART,%d0
        beq.s   9f
1:      movel   %d1,PLAY_BANK
        movel   %d0,PLAY_PART
        clrl    XF_CONTEXT_VALID
9:      moveml  %sp@,%d0-%d2
        lea     %sp@(12),%sp
        rts
